### ISSUE TITLE
[FEATURE] Download all files and photos by default

### ISSUE THREAD

**Issue by tensiondriven** [mandarons/icloud-docker#137]
**Use case**
As an icloud user interested in keeping local files, I want to easily backup my entire icloud drive with minimal effort and configuration

**Describe the solution you'd like**
Currently it appears that the config yaml requires specifying specific file types, icloud drive folders and photo albums.  By default, I would expect it to download everything, and only restrict what is downloaded when specified.

**Describe alternatives you've considered**
I guess I can specify Library and Desktop and call it a day.  But this won't get all file types, if I'm reading the config file correctly

**Additional context**
As an aside, the comments in the config.yaml could be improved to add additional context specigying that "Only these will be downloaded, there is no way to download all"
Additionally, under Folders", specify default folders for icloud accounts: Documents, Desktop, etc. instead of "folder1", folder2", "folder3" etc.

**Comment by tensiondriven** [comment]
It occurs to me based on [this comment](https://www.reddit.com/r/docker/comments/lntwzr/comment/go8d0di/?utm_source=reddit&utm_medium=web2x&context=3) that maybe the default behaviour is to download everything if the filters are not set, however that isn't clear from the docs.  It might just be a matter of udpating documentation and config file to satisfy my needs.

**Comment by mandarons** [comment]
Updated the [README](https://github.com/mandarons/icloud-drive-docker#readme).
