### ISSUE TITLE
[BUG] PUID, PGID, UMASK variables not honoured

### ISSUE THREAD

**Issue by cyruz-git** [mandarons/icloud-docker#140]
PUID and PGID variables are not honoured, all the files/directories are owned by root with umask 022 even if I set UMASK=002.

**Comment by mandarons** [comment]
Try running the container with ```--user``` option.

**Comment by cyruz-git** [comment]
Sadly it doesn't work, the container doesn't startup correctly, even if I start from zero.

**Comment by happyeddie** [comment]
> Try running the container with `--user` option.

When configured with `-user`, a permission error is thrown.
```PermissionError: [Errno 13] Permission denied: '/app/icloud.log'```

**Comment by mandarons** [comment]
Fixed by #206
