### ISSUE TITLE
[BUG] iCloud Drive documents given random characters in filename

### ISSUE THREAD

**Issue by mvnixon** [mandarons/icloud-docker#150]
**Describe the bug**
When syncing iCloud Drive, some files are given random characters in the title. The documents themselves still open fine, but the titles are completely random, i.e. :\�7�8cmYX�҃������ǗPApq,��`�?��k������v�B.pages

I have also witnessed some files being putting in subfolders with arbitrary names i.e. _5OUU6~A 

I do think there is a correlation between files that are shared via 'iCloud collaboration' i.e. a shared keynote document with multiple people working on it.

I also see that the access dates is updated to the time of sync even if the document has not been accessed for years. 

**To Reproduce**

1. Have a collaborative pages, numbers, or keynote document
2. on sync random letters/naming convention inherited.

**logs**

(replaced folder name with folder-name and file-name - consistent naming)

Downloading /app/icloud/drive/folder-name/file-name.pages ...[0m
Unpacking /app/icloud/drive/folder-name/file-name.pages.gz to /app/icloud/drive/folder-name[0m
Unpacking /app/icloud/drive/folder-name/file-name.pages.zip to /app/icloud/drive/folder-name[0m
Successfully unpacked the package /app/icloud/drive/folder-name/file-name.zip.[0m
Successfully unpacked the package /app/icloud/drive/folder-name/file-name.pages.gz.[0m
Failed to download /app/icloud/drive/folder-name/file-name.pages: [Errno 2] No such file or directory[0m

**Comment by mandarons** [comment]
Try upgrading to latest version (1.15.0) and see if it solves this problem. We released a new feature to normalize file paths.
