### ISSUE TITLE
Cannot download files with reserved characters in path

### ISSUE THREAD

**Issue by charlesvestal** [mandarons/icloud-docker#151]
**Describe the bug**
I noticed a file failing to  download, and I am guessing that having a colon in the name is causing the sync command to fail

2023-09-20 09:29:46,298 :: ERROR :: root :: sync_drive.py :: 196 :: Failed to download /app/icloud/drive/Atom/Piano Roll 2.0.3/Logs/Session 2023-07-02 16:17:38.log: [Errno 22] Invalid argument: '/app/icloud/drive/Atom/Piano Roll 2.0.3/Logs/Session 2023-07-02 16:17:38.log'

I'm not sure how this was created in the first place (maybe iOS allows it?), but it might be worth allowing to rename on sync if filenames or folders contain special / reserved characters.

**Comment by charlesvestal** [comment]
I'm guessing this is actually related to my use of ExFAT as a destination directory. A quick test on my server lets me create a "test:test" folder on my ext4 volume, but fails with "invalid argument" on ExFAT, but noting on MacOS, it automatically replaces the characters when viewed in finder. 
<img width="922" alt="SCR-20230920-jgpn" src="https://github.com/mandarons/icloud-drive-docker/assets/1034155/07fa0064-7499-4f57-8229-d43b5052441e">

**Comment by mandarons** [comment]
Yeah, sounds like ExFAT doesn't allow `:` as a valid filename character (https://en.wikipedia.org/wiki/ExFAT).

Can you use some modern filesystem (e.g. ext4) instead of ExFAT? This will also resolve your #152 problem.

**Comment by charlesvestal** [comment]
I _can_, but would have preferred it for interoperability with mac, in case of needing to restore. But if that’s the only option, I’ll move over!

**Comment by mandarons** [comment]
Yes, please move to some other modern filesystem. This is a corner case and not worth looking into it especially knowing that there is a workaround (upgrade to modern filesystem).
