### ISSUE TITLE
iMovie library are reported as different sizes

### ISSUE THREAD

**Issue by charlesvestal** [mandarons/icloud-docker#152]
After a successful sync, I'm seeing some files redownloaded because of a size mismatch.

as an example,

023-09-20T07:33:00.398548787Z 2023-09-20 09:33:00,397 :: INFO :: root :: sync_drive.py :: 110 :: Changes detected: local_modified_time is 1682483548, remote_modified_time is 1682483548, local_package_size is 3357967527 and remote_package_size is 3357967526.
2023-09-20T07:33:00.887576520Z 2023-09-20 09:33:00,886 :: INFO :: root :: sync_drive.py :: 186 :: Downloading /app/icloud/drive/Documents/_Personal/Art/Good Kid.imovielibrary ...
2

Off by one byte, but redownloading 3.5gb (as expected). I'm not sure if this is an issue with iMove libraries or something with how my files are written locally (on a raspberry pi writing to an ExFAT volume).

**Comment by mandarons** [comment]
Sounds like something interesting going on with local file. I haven't seen this problem until now. Is it happening only to this specific file? Are you opening this file in any application after downloading it?

**Comment by charlesvestal** [comment]
nope! happy to provide the file  if useful. for now i’ve just zipped it to prevent the change, but wanted to report if useful. On Sep 21, 2023, at 17:39, Mandar Patil ***@***.***> wrote:﻿
Sounds like something interesting going on with local file. I haven't seen this problem until now. Is it happening only to this specific file? Are you opening this file in any application after downloading it?

**Comment by mandarons** [comment]
Let's see if moving to modern filesystem fixes this problem. If not, please share the file to reproduce it on my end and possibly fix it.
