### ISSUE TITLE
[FEATURE] support (if possible) advanced data protection

### ISSUE THREAD

**Issue by dmuiX** [mandarons/icloud-docker#166]
**Use case**
As an adp enabled iCloud user, I want to use your app with adp enabled.

**Describe the solution you'd like**
support adp ;)

**Describe alternatives you've considered**
For me disable it is no alternative as I don’t want Apple to have access to my data. So no alternative. 

**Additional context**

**Comment by dmuiX** [comment]
Already found an answer

**Comment by davefedele** [comment]
> Already found an answer

Care to share what you found? thanks
