### ISSUE TITLE
[BUG] ERROR :: icloudpy.base :: base.py :: 186 :: Bad Gateway (502)

### ISSUE THREAD

**Issue by TheIronboy** [mandarons/icloud-docker#167]
**Describe the bug**
I get this error spammed in my logs, and i don't understand why

**To Reproduce**
I used docker compose to run the container, here is the config:

version: "3.4"

services:
  icloud:
    hostname: docker-icloud-drive
    container_name: icloud-docker
    image: mandarons/icloud-drive:latest
    environment:
      - PUID=1000
      - GUID=100
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yaml:/app/config.yaml
      - ./session_data:/app/session_data
      - /mnt/Pi-NAS_DATA/Pi-NAS/theironboy:/app/icloud
    restart: unless-stopped

**Expected behavior**
It should sync my drive and photos without getting this error spammed in the logs

**Screenshots**
![image](https://github.com/mandarons/icloud-drive-docker/assets/66006359/da74ab87-3e2e-43b1-89b4-d34809127cb8)

**Comment by mandarons** [comment]
Do you have advanced data protection enabled?

**Comment by TheIronboy** [comment]
no, i disabled it yesterday

**Comment by mandarons** [comment]
Try deleting all the folders, container etc. and recreate them. Log into icloud.com and make sure everything looks good. 

Gateway errors usually indicate some network issue and service unavailable is related to your iCloud settings.

**Comment by TheIronboy** [comment]
okay, problem solved, i was using pi-hole and it was blocking icloud for some reason.
thanks!
