### ISSUE TITLE
Option to keep the original file name

### ISSUE THREAD

**Issue by Hant0r** [mandarons/icloud-docker#170]
Would it be possible to add an option to keep the original file names of the images after downloading?

Currently the file names are called e.g:
IMG_1234__original__QVhWvENlSW1lL4FCOZZoVnYwVRpFYlRIbXM4MQ==.JPG

Why aren't they just called like the original "IMG_1234.JPG"?

Or am I doing something wrong?

**Comment by mandarons** [comment]
This naming scheme is required for downloading all the photos. The app gives options to download certain quality of photos (original, medium or thumbnail). Hence, quality is included in the file name. There was a problem with multiple iCloud albums containing different photos but with same filename. This created a conflict in downloading that image to `all` folder - hence the unique ID is included in the filename.

There is no option to keep original filename as it will break the all photos and/or all qualities use case.
