### ISSUE TITLE
[FEATURE] Option to download photos/videos with all EXIF information

### ISSUE THREAD

**Issue by afreuden** [mandarons/icloud-docker#179]
**Use case**
As a user that categorizes photos by time/location taken, I want to have the option to download photos/videos with the complete and original EXIF information so in a disaster recovery event all photos and videos have the original metadata.

**Describe the solution you'd like**
An option in the configuration file to include or exclude all EXIF information in downloaded photos/videos. This should be an end user configurable option, acknowledging that other users may prefer to not include this information in photos/videos for privacy reasons.

**Describe alternatives you've considered**
Current alternative is using Synology Drive to backup photo library to a NAS as a secondary backup which includes the EXIF data natively, however this is a manual workaround (a physical schedule to leave my phone unlocked, on and connected to my home WiFi for the backup to complete) rather than being automated on the NAS/Server

**Additional context**
Nil

**Comment by mandarons** [comment]
Is it possible through icloud.com? Looks like it has three options for downloading photos:

![image](https://github.com/mandarons/icloud-drive-docker/assets/50469173/3c0681d5-1991-4377-9808-b7dbe79c9165)

**Comment by afreuden** [comment]
Hi @mandarons,
Apologies I believe I have been chasing a red herring. Short hand is I think this is not an issue with icloud-drive-docker but maybe an issue with Synology DSM reading EXIF data. Have spot checked various images that were all downloaded via the following methods:

- iCloud.com as unmodified original
- iCloud.com as highest resolution
- iCloud.com as most compatible
- icloud-drive-docker 
- iOS Synology Drive app

All contain the correct EXIF data as expected when viewed on Windows 10, however for whatever reason some specific photos report as having no EXIF data when viewed in Synology DSM, however this issue is consistent across icloud-drive-docker and the Synology Drive Client so I suspect this is a DSM issue. I was just really unfortunate with my initial spot checking of images before logging this feature request. Sorry!
