### ISSUE TITLE
Make photo sync optional

### ISSUE THREAD

**Issue by gniting** [mandarons/icloud-docker#181]
**Use case**
I don't use Apple Photo's to manage my pictures, and therefore have no need to sync them.

**Describe the solution you'd like**
An option whereby photo sync is optional.

**Describe alternatives you've considered**
N/A

**Additional context**
Maybe this is already possible by simply commenting out the `photos:` section in the yaml file?

**Comment by tymmej** [comment]
You can comment out whole section.

**Comment by mandarons** [comment]
> You can comment out whole section.

This should work.

**Comment by gniting** [comment]
That works!
