### ISSUE TITLE
[BUG] All photos are synced while All_Albums is true?

### ISSUE THREAD

**Issue by serhatVIRT** [mandarons/icloud-docker#183]
**Describe the bug**
I think that this is feature is not working properly while using the configuration at the bottom. I assume that with this configuration is set it would only download the albums and not all Photo's (Recents folder in iCloud). Or I don't get it how to sync/download only contents from albums and not the entire iCloud.

**To Reproduce**

1. Edit config file
2. set all_albums: true
3. Empty album list.

**Expected behavior**
Sync and download ONLY albums, not all photo's, just the albums included the photo's/video's.

**Configuration**
photos:
  destination: "photos"
  remove_obsolete: false
  sync_interval: 20
  all_albums: true # Optional, default false. If true preserve album structure. If same photo is in multiple albums creates duplicates on filesystem
  folder_format: #"%Y/%m" optional, if set put photos in subfolders according to format. Format cheatsheet - https://strftime.org
  filters:
    # List of libraries to download. If omitted (default), photos from all libraries (own and shared) are downloaded. If included, photos only
    # from the listed libraries are downloaded.
    #libraries:
    #  - PrimarySync # Name of the own library
    # if all_albums is false - albums list is used as filter-in, if all_albums is true - albums list is used as filter-out
    # if albums list is empty and all_albums is false download all photos to "all" folder. if empty and all_albums is true download all folders
    albums:
    file_sizes:
      # valid values are original, medium and/or thumb
      - "original"
      #- "medium"
      #- "thumb"

**Comment by tymmej** [comment]
There are some default albums. The list can be viewed at https://github.com/mandarons/icloudpy/blob/24c37cac18ae32733713a05112a0a1e6b31124f4/icloudpy/services/photos.py#L25

You cen filter out them using `albums` key (part of my config):
```
   albums:
     # - "All Photos"
     # - "Hidden"
     - "Time-lapse"
     - "Videos"
     - "Slo-mo"
     - "Bursts"
     - "Favorites"
     - "Panoramas"
     - "Screenshots"
     - "Live"
     - "Recently Deleted"
```

**Comment by mandarons** [comment]
> There are some default albums. The list can be viewed at https://github.com/mandarons/icloudpy/blob/24c37cac18ae32733713a05112a0a1e6b31124f4/icloudpy/services/photos.py#L25
> 
> You cen filter out them using `albums` key (part of my config):
> 
> ```
>    albums:
>      # - "All Photos"
>      # - "Hidden"
>      - "Time-lapse"
>      - "Videos"
>      - "Slo-mo"
>      - "Bursts"
>      - "Favorites"
>      - "Panoramas"
>      - "Screenshots"
>      - "Live"
>      - "Recently Deleted"
> ```

@serhatVIRT This should work.

**Comment by serhatVIRT** [comment]
Thanks guys! It worked!
