### ISSUE TITLE
[FEATURE] Support all photo versions in photo filter

### ISSUE THREAD

**Issue by Chaldron** [mandarons/icloud-docker#188]
icloudpy supports a number of photo versions (original, thumbnail, etc. [see here](https://github.com/mandarons/icloudpy/pull/28/commits/e78ac9d30294ca4f981ffe325655617d71b8a975)), but `get_photos_filters` in `config_parser.py` only permits "original", "medium", and "thumb". I have built the image locally to accept all versions supported by icloudpy, and I can confirm that it correct downloads the "original_alt" files (which in my case happen to be RAW files). I think an easy solution is to just duplicate the list used in icloudpy, but maybe a better way is for icloudpy to expose which versions it supports so clients can refer to it. I'd be happy to put up PRs for either of these methods. By the way, thank you for developing this very useful project :)

Log output:
```
icloud-sync  | 2024-02-10 04:40:19,350 :: WARNING :: root :: config_parser.py :: 340 :: Skipping the invalid file size original_alt, valid file sizes are original,medium,thumb.
```

**Comment by mandarons** [comment]
@Chaldron Please feel free to submit PR(s).
