### ISSUE TITLE
[BUG] v1.18.1 binary path + login doesn't persist

### ISSUE THREAD

**Issue by mpepping** [mandarons/icloud-docker#207]
**Describe the bug**

Bumped to v1.18.1 (from v1.18.0) and that seems to introduce two issues.

1. The `icloud` command isn't in the container image path anymore. It has to be specified as `/venv/bin/icloud` (e.g., via `docker exec`)
2.  The app remains in a `Retrying login every 600 seconds` loop after specifying an account. Not sure if that is related to the PATH issue?

Reverting back to v1.18.0 resolves both issues.

**To Reproduce**

1. Upgrade to v1.18.1
1. Run `docker exec -it icloud /bin/sh -c "icloud --username=<icloud-username> --session-directory=/app/session_data"`
1. See `icloud command not found` error

**Expected behavior**
Running the command should execute the command

**Screenshots**

**Configuration**
If applicable, please share the configuration details

**Additional context**

**Comment by mandarons** [comment]
Oops.. sorry about that. Working on the fix...
