### ISSUE TITLE
[BUG] Container not starting/ stuck in loop - unknown user/group icd:icd

### ISSUE THREAD

**Issue by weichmut** [mandarons/icloud-docker#211]
**Describe the bug**
Container is not starting and stuck in loop.
No matter what group id or user is used.

**To Reproduce**

1. Use CA Container in Unraid or create custom.
2. Start container with default settings
3. See error

**Screenshots**
![Bildschirmfoto 2024-05-27 um 19 22 54](https://github.com/mandarons/icloud-drive-docker/assets/151665512/a1ee4f6f-7a8d-41ba-b9bd-94aa4d39c464)

**Configuration**

docker run
  -d
  --name='icloud-drive-sync'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Unraid-Server"
  -e HOST_CONTAINERNAME="icloud-drive-sync"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e '/app/config.yaml'='/mnt/user/appdata/icloud-drive-sync/config.yaml'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://help.apple.com/assets/60AD31069883FC55AC222539/60AD310B9883FC55AC22254A/de_DE/712e44cf3701cf5bc9580c9367fa5526.png'
  -v '/mnt/user/icloud-drive-sync/':'/app/icloud/':'rw'
  --restart always 'mandarons/icloud-drive' 
82ae4dc06f1004b6df5c4e939730201b693f34299c6285da100ea8eb89cfcc0b

**Comment by mandarons** [comment]
From https://www.reddit.com/r/unRAID/s/kTIkei5Jbw

> Toggle the Basic/Advanced switch on top right corner, set Extra Parameters: to --user 99:100 if it's not.

**Comment by weichmut** [comment]
Solved by removing PUID and PGUID entirely in Docker settings.
I also changed the variables according to the newer installation parameters on GitHub.

![Bildschirmfoto 2024-05-27 um 20 07 45](https://github.com/mandarons/icloud-drive-docker/assets/151665512/ffb7c50c-8b6b-413c-878c-1a04db63b707)

Maybe update the Unraid template?

**Comment by benblustey** [comment]
@weichmut thank you for this direction. Also on unRaid, was able to get the container up and go through the authentication process. Although, still not functioning, nothing syncing, no errors, session_data being populated.
