### ISSUE TITLE
[BUG] Immediate Crash

### ISSUE THREAD

**Issue by rix1337** [mandarons/icloud-docker#215]
**Describe the bug**

**To Reproduce**
1. Install on UNRAID
2. Start Container
3. Container stops, no error message shown

**Expected behavior**
Container Runs or shows crash notification

**Screenshots**
<img width="1180" alt="image" src="https://github.com/mandarons/icloud-drive-docker/assets/9930448/a8da4f1d-4384-486f-bf99-0a79b1b84172">

**Configuration**
<img width="1265" alt="image" src="https://github.com/mandarons/icloud-drive-docker/assets/9930448/3157286a-2ef2-49c3-be6b-24aaf5dad54e">

**Additional context**
Has been running without problems for months. Have not touched the config file. App crashes hard starting a week ago.

**Comment by bajire72** [comment]
Hello, you have to remove the UID and the UMASK in the unraid template :) 

Have a good day.

**Comment by mandarons** [comment]
The way I implemented `PUID` and `PGID` is causing problem in UNRAID. Try removing it.

**Comment by rix1337** [comment]
yup, that seems to have worked. thank you
