### ISSUE TITLE
[FEATURE] SMTP configurable Mail Subject

### ISSUE THREAD

**Issue by nicx** [mandarons/icloud-docker#217]
As a family administrator of multiple iCloud-drive-docker instances, I want to know which of my family members need to reauthenticate so that I can directly support the right family member with our searching trough all my container logs.

As a simple solution the subject of the mail for reauthication should be made configurable. As of now it's fixed "icloud-docker: Two step authentication required". This could be the default value of a new configuration option in the config YAML. With that option I could configure it for example this way: "icloud-docker: Two step authentication required for User XYZ"

As an alternative the content of the mail could be a little bit more dynamic, so that the correct username is already filled out into the body (via the already configured username in the yaml). With that I could simpler do a copy and paste of the command :) 

today:

```
Two-step authentication for iCloud Drive, Photos (Docker) is required.
Please login to your server and authenticate. Please run -
`docker exec -it --user=icd icloud /bin/sh -c "icloud --username=<icloud-username>
--session-directory=/app/session_data"`.

```

tomorrow:
```
Two-step authentication for iCloud Drive, Photos (Docker) is required.
Please login to your server and authenticate. Please run -
`docker exec -it --user=icd icloud /bin/sh -c "icloud --username=asdfa@icloud.com
--session-directory=/app/session_data"`.
```

Maybe both features are making sense... It's for sure up to you! :)

**Comment by mandarons** [comment]
Yup.. totally makes sense. Thank you for suggesting this feature.
