### ISSUE TITLE
[BUG] Changing Ownership of files running every container restart leads to no synchronization at all because a lot of files on my nas

### ISSUE THREAD

**Issue by nicx** [mandarons/icloud-docker#218]
I do a nighly restart of all my docker containers because of backup jobs. At every restart of the icloud-docker container firstly there is the "changing ownership" part running. only after this has run through does the actual synchronization start. i have a lot of files on my iCloud account and unraid nas, so the first step takes hours. according to the log file, it never ends. therefore it never syncs.

i have manually assigned the files locally to the correct owner. however, the first step is repeated every time the container is started, regardless of whether the ownership is correct or not.

In the log file I can see this status:

```
====================================================
To support this project, please consider sponsoring.
https://github.com/sponsors/mandarons
https://www.buymeacoffee.com/mandarons 
====================================================

Using UID as 1000, GID as 1000 and UMASK as 022...
Changing ownership of /app ... This operation may take significantly longer depending on number of files in your local copy of icloud.

```

in another container of another family member with a small amount of files I can see this log file:

```
https://github.com/sponsors/mandarons
https://www.buymeacoffee.com/mandarons 
====================================================

Using UID as 1000, GID as 1000 and UMASK as 022...
Changing ownership of /app ... This operation may take significantly longer depending on number of files in your local copy of icloud.
Loading config from /app/config.yaml ...
```

As you can see in the second case the loading of the config file happens correctly and the sync starts. in the first case there is no sync starting at all.

**Comment by denishartl** [comment]
Can confirm, same thing happening for me. Also running on UNRAID with multiple containers. One for files, one for photos in my case.
