### ISSUE TITLE
[FEATURE] Telegram Message for notifications about expired/missing 2FA credentials

### ISSUE THREAD

**Issue by SandraCHC** [mandarons/icloud-docker#219]
At the moment you send the notifications about expired/missing 2FA credentials only to smtp (if I understand your readme). Can you optional send this with telegram?

**Comment by mandarons** [comment]
It is already available. Please include below snippet in `config.yaml` > `app` section. From: https://github.com/mandarons/icloud-drive-docker?tab=readme-ov-file#sample-configuration-file 

```
telegram:
  bot_token: <your Telegram bot token>
  chat_id: <your Telegram user or chat ID>
```

**Comment by SandraCHC** [comment]
Thank you :)
