### ISSUE TITLE
[BUG] 2FA Prompt Every Time Starting the Docker Container

### ISSUE THREAD

**Issue by s485lee** [mandarons/icloud-docker#236]
**Describe the bug**
2FA popup shows up on my Apple devices every time the docker container is restarted. Unable to sync my iCloud drive. 

Running the following command:
`icloud --username= --session-directory=/app/session_data` 
Returns:
`root@XXXXXXXX:/app# `

**To Reproduce**
Restart Docker Container

**Expected behavior**
Successful login, then download contents of my iCloud drive.

**Screenshots**
<img width="1312" alt="Screenshot 2024-06-28 at 11 15 55 PM" src="https://github.com/mandarons/icloud-drive-docker/assets/155126361/9047c18b-4f5a-45ae-9399-77e7b765cf97">
<img width="1312" alt="Screenshot 2024-06-28 at 11 17 28 PM" src="https://github.com/mandarons/icloud-drive-docker/assets/155126361/b822aab9-e298-4bc3-a55c-247c862bc371">

**Configuration**
<img width="1054" alt="image" src="https://github.com/mandarons/icloud-drive-docker/assets/155126361/afc862cb-c503-4dab-9180-e3f2fb191726">

**Additional context**

**Comment by mandarons** [comment]
Looks like you're using older `session_data` path. Please use the new path:
From [README](https://github.com/mandarons/icloud-drive-docker/blob/main/README.md)
```
# Login manually if ENV_ICLOUD_PASSWORD is not specified and/or 2FA is required
docker exec -it icloud /bin/sh -c "icloud --username=<icloud-username> --session-directory=/config/session_data"
```

**Comment by s485lee** [comment]
Ok that solved it and now my drive is syncing. I will post my unraid plugin configuration for any unraid user having the same problem:

<img width="1065" alt="image" src="https://github.com/mandarons/icloud-drive-docker/assets/155126361/938883ee-153e-487a-87a1-1b9ffd979602">
