### ISSUE TITLE
Single-fire option

### ISSUE THREAD

**Issue by robdejonge** [mandarons/icloud-docker#35]
**Use case**
Running the container as a script, just execute a single cycle

**Describe the solution you'd like**
While the container could be up and running and set with whatever poll frequency desired, for my use-case the polling is infrequent and upon request really. I'd like to be able to run the container with a single sync cycle instead of polling. Maybe if it's set to 0 or something?

**Describe alternatives you've considered**
I could start the container upon request, and have it automatically stopped after a set amount of time that ensures a sync completes but no second sync is started. While it would work, it's not exactly an elegant solution.

**Comment by robdejonge** [comment]
Was reading [the source code](https://github.com/mandarons/icloud-drive-docker/blob/main/src/sync.py) and noticed it actually breaks if the `sync_interval` in the configuration file is set to -1. Confirmed to work as expected. So, feature already exists!

**Comment by mandarons** [comment]
I love it when the issues gets closed without me doing anything. Thank you for taking some time to look into the code. 👍
