### ISSUE TITLE
[FEATURE] make renaming of photos on download configurable

### ISSUE THREAD

**Issue by nicx** [mandarons/icloud-docker#42]
As a user I want to download all my photos independently form albums in a flat way. As of today this is working, but the photos are renamed to "IMG_4727__original.HEIC". I want them to keep the original name, so the photo should keep "IMG_4727.HEIC" as name for the original filesize.

Therfor it would be great if the renaming function would be optional. Or even better: the "append" variable for name is configurable for each file size.

As an alternative a quick solution could be that the "original" file size just keeps the original filename, the other filesizes could be renamend to "filename_filesize.heic" (maybe without the double __)

**Comment by mandarons** [comment]
Removal of `__original` for original quality make sense. Allowing user to customize file naming can be error prone.
