### ISSUE TITLE
iCloud Password Not Saving

### ISSUE THREAD

**Issue by roberto2lini** [mandarons/icloud-docker#47]
Hi! Thanks for your work. 

Im having some trouble getting it to save the iCloud password. I do get a login notification e-mail from icloud once I initially setup the authentication, but it doesnt seem to get saved in the keychain/start to sync in the container. 

More users have reported this here: 

https://www.reddit.com/r/docker/comments/s4cqd5/dockerized_icloud_now_with_photos/?user_id=71826092&web_redirect=true

Steps to Reproduce: 
1.  Setup Container via Docker Hub - docker run --name icloud -v /var/lib/docker/volumes/icloud-data:/app/icloud mandarons/icloud-drive 
2.  Set Authentication
docker exec -it icloud /bin/sh -c "icloud --username=changeme@mail.com"
Enter iCloud password for changeme@mail.com:
Save password in keyring? [y/N]: y

Two-step authentication required.
Please enter validation code
(string) --> 00000

3. Container Outputs: 

password is not stored in keyring. Please save the password in keyring.

OS Info: 
Description:	Ubuntu 20.04.3 LTS

Docker Version: 

Docker version 20.10.12, build e91ed57

**Comment by mandarons** [comment]
I see that in your `docker run` command above, you're not mapping `config.yaml`.

Sorry, my bad - I see that in [README](https://github.com/mandarons/icloud-drive-docker#readme), I didn't specify `config.yaml` file mapping in `docker run` command but I do have it in `docker-compose.yaml` example. I updated the [README](https://github.com/mandarons/icloud-drive-docker#readme).

Please make sure that the username `changeme@mail.com` is exactly same as the one you have in `config.yaml > app > credentials > username` field and try again.

**Comment by roberto2lini** [comment]
That works for me! 👍 Thanks a lot!
