### ISSUE TITLE
[FEATURE] Ignore Files

### ISSUE THREAD

**Issue by reedhaffner** [mandarons/icloud-docker#48]
**Use case**
I have some projects in my iCloud documents with .git and node_module folders that i don't really need to sync.

**Describe the solution you'd like**
Add an `ignore` to the yml. Allow direct paths or asterisks
eg,
``` yaml
ignore:
  - */node_modules # ignore node modules
  - /projects/examples/.git # ignore specific git folder
```

**Comment by jeff47** [comment]
Agreed, would be a very useful addition both for paths and extensions.  

For backups, I prefer the strategy of "back it up unless I say not to" instead of "only back it up if I say so".
