### ISSUE TITLE
Hang during drive downloads

### ISSUE THREAD

**Issue by edsw** [mandarons/icloud-docker#58]
**Describe the bug**
The sync process consistently hangs during downloading large Drive objects. The log outputs "Downloading [file name]..." but never returns or prints other output, even after waiting hours. The Docker task continues to run, however. Small files preceding the large file download fine.

**Configuration**
Latest commit from the Git repo. Docker version 20.10.12, build e91ed57.

I also tried cloning the repo and adding additional lines of verbose output to identify exactly where the download hangs. The code enters the `copyfileobj` call on line 100 but does not return from it.

**Comment by mandarons** [comment]
How big is the file?

**Comment by edsw** [comment]
Various sizes between 4GB and 23GB. Sometimes the larger files transfer OK, but often they just hang at that `copyfileobj` call. 

Edit: The script just stopped processing on a much smaller 24MB file, as well.

**Comment by mandarons** [comment]
Can you check if file size of the file being downloaded is increasing while the script appears to be stuck at `copyfileobj`? 
You can use `tail -f -c 1 <file_path> | pv > /dev/null` to check if file is growing.
Did it work in the past?

**Comment by edsw** [comment]
> Can you check if file size of the file being downloaded is increasing while the script appears to be stuck at copyfileobj?
You can use tail -f -c 1 <file_path> | pv > /dev/null to check if file is growing.

The file is not growing. `pv` shows `[0.00 B/s]` over a time period of a few minutes. 

> Did it work in the past?

No, I've never had the script successfully complete a sync against my iCloud Drive. It always ends up hanging on a file at some point. When I restart the container it will make progress past the point of past failures, but then eventually fail again.

The file that its currently hung on, in my most recent container restart, stopped downloading at ~3MB out of a ~24MB file.

**Comment by mandarons** [comment]
Okay. Something is unique about your iCloud Drive/environment that's making it tricky. Let's see if we can isolate the problem.

Can you please execute below script 'inside' the container?

```python
import time
import shutil
import requests

start = time.time()

shutil.copyfileobj(requests.get('https://releases.ubuntu.com/20.04.3/ubuntu-20.04.3-desktop-amd64.iso', stream=True).raw, open("ubuntu.iso", "wb"))
end = time.time()
print(f'execution time: {end - start} seconds')
```
And then execute below script 'inside' the container -
```python
import time
import shutil
import requests

start = time.time()

shutil.copyfileobj(requests.get('https://releases.ubuntu.com/20.04.3/ubuntu-20.04.3-desktop-amd64.iso', stream=True).raw, open("ubuntu.iso", "wb"), 100*1024*1024)
end = time.time()
print(f'execution time: {end - start} seconds')
```
Then run both the scripts above, outside the container (on your host system, using python 3.9.10). We are trying to see if anything wrong with the container.

**Comment by edsw** [comment]
Thanks. Here are the results of the tests:

- Inside container, no buffer size provided `execution time: 84.42804741859436 seconds`
- Inside container, buffer size provided `execution time: 83.96192908287048 seconds`
- Outside container, no buffer size provided `execution time: 26.988187074661255 seconds`
- Outside container, buffer size provided `execution time: 29.866533756256104 seconds`

**Comment by mandarons** [comment]
@edsw do you still see this issue?

**Comment by mandarons** [comment]
@edsw are you still seeing this issue?
