### ISSUE TITLE
how to download entire iCloud Drive?

### ISSUE THREAD

**Issue by flyingwasabi** [mandarons/icloud-docker#89]
instead of setting some specific folders and file extensions, is it possible to just download the entire iCloud Drive?

thanks,

**Comment by Mrc527** [comment]
Sure, I do exactly that using this configuration:
`drive:
destination: "drive"
remove_obsolete: true
sync_interval: 3600`

**Comment by flyingwasabi** [comment]
> Sure, I do exactly that using this configuration:
> `drive: destination: "drive" remove_obsolete: true sync_interval: 3600`

thanks a lot!
