### ISSUE TITLE
Synchronize the content of a folder

### ISSUE THREAD

**Issue by draco1544** [mandarons/icloud-docker#96]
Hi !

How I can synchronize my iCloud Drive folder "Document/Test" into the container folder "icloud" without the container folder look like "icloud/Document/Test". I juste want the content of "Document/Test" in the "icloud" folder of the container. How I can do that in the config file ?

**Comment by mandarons** [comment]
Currently, there is no way to do that. The app will preserve folder structure, same as server. This is required to compare if the file has changed locally, with server and decide of redownload is required or not.
